const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
function load(file,context,names){const code=fs.readFileSync(path.resolve(root,file),'utf8').replace(/^import .*;\r?$/gm,'').replace(/\bexport /g,'');vm.runInContext(code+'\nthis.api={'+names.join(',')+'};',context);return context.api;}
const math=load('BP/scripts/machinery/generators/combustionSimulation.js',vm.createContext({}),['COMBUSTION','getCombustionStats','burnSolidFuel']);
const near=(a,b)=>assert(Math.abs(a-b)<1e-7, a+' != '+b);
const bounds={min:{x:0,y:0,z:0},max:{x:4,y:4,z:4}};
function registry(){const listeners=[],loads=[],queue=[];const system={afterEvents:{scriptEventReceive:{subscribe(fn){listeners.push(fn);}}},sendScriptEvent(id,message){queue.push({id,message});}};const world={afterEvents:{worldLoad:{subscribe(fn){loads.push(fn);}}}};
const uc=load('../UtilityCraft/BP/scripts/config/recipes/fuel.js',vm.createContext({system,console,DoriosLib:{registry:{registerFuel(payload){loads.push(()=>system.sendScriptEvent('utilitycraft:register_fuel',JSON.stringify(payload)));}}}}),['solidFuels']);
const hm=load('BP/scripts/config/recipes/solidFuels.js',vm.createContext({system,world}),['solidFuels','findSolidFuel']);
function drain(){let n=0;while(queue.length){assert(++n<1000);const event=queue.shift();for(const fn of listeners)fn(event);}}assert.equal(uc.solidFuels.length,0);assert.equal(hm.solidFuels.length,0);loads.forEach(fn=>fn());assert(queue.every(e=>e.id==='utilitycraft:register_fuel'));drain();return{uc,hm,system,drain};}
test('HM receives the actual Furnator registry and custom updates without a second default list',()=>{const r=registry();assert.deepEqual(JSON.parse(JSON.stringify(r.hm.solidFuels)),JSON.parse(JSON.stringify(r.uc.solidFuels)));assert.equal(r.hm.findSolidFuel('minecraft:coal').de,8000);assert.equal(r.hm.findSolidFuel('utilitycraft:compressed_oak_wood_4').de,15000000);r.system.sendScriptEvent('utilitycraft:register_fuel',JSON.stringify({coal:9000,'addon:crystal':12345}));r.drain();assert.equal(r.hm.findSolidFuel('minecraft:coal').de,9000);assert.equal(r.hm.findSolidFuel('addon:crystal').de,12345);const count=r.hm.solidFuels.length;r.system.sendScriptEvent('utilitycraft:register_fuel',JSON.stringify({coal:9500}));r.drain();assert.equal(r.hm.solidFuels.length,count);assert.equal(r.uc.solidFuels.length,count);assert.equal(r.hm.findSolidFuel('minecraft:coal').de,9500);assert.equal(r.uc.solidFuels.find(f=>f.id==='coal').de,9500);});
test('Each coal yields exactly 10000 DE, including the saved remainder',()=>{const r=math.burnSolidFuel({ticks:4,rate:32,reserve:0,fuelValue:8000,itemCount:1,energySpace:1e9});assert.equal(r.items,1);near(r.energy,160);near(r.reserve*1.25+r.energy,10000);});
test('Bulk stack consumption, full storage and fractional space conserve fuel',()=>{const r=math.burnSolidFuel({ticks:80,rate:10000,reserve:250,fuelValue:8000,itemCount:64,energySpace:1e9});assert.equal(r.items,64);near(r.energy+r.reserve*1.25,(250+64*8000)*1.25);const small=math.burnSolidFuel({ticks:4,rate:32,reserve:0,fuelValue:8000,itemCount:1,energySpace:.25});near(small.energy,.25);near(small.reserve*1.25+small.energy,10000);const full=math.burnSolidFuel({ticks:4,rate:32,reserve:10,fuelValue:8000,itemCount:1,energySpace:0});assert.equal(full.items,0);assert.equal(full.reserve,10);});
test('4/20/80 tick batches produce equal results at sustained fuel supply',()=>{function run(ticks){let reserve=0,energy=0,items=64;for(let t=0;t<80;t+=ticks){const r=math.burnSolidFuel({ticks,rate:32,reserve,fuelValue:8000,itemCount:items,energySpace:1e9});reserve=r.reserve;energy+=r.energy;items-=r.items;}return{reserve,energy,items};}assert.deepEqual(run(4),run(20));assert.deepEqual(run(20),run(80));});
test('Size uses empty volume and rejects special interior components',()=>{const stats=math.getCombustionStats(bounds,{air:26,energy_cell:1});assert.equal(stats.maxRate,3328);assert.equal(math.getCombustionStats(bounds,{air:25,energy_cell:1,thermo_core:1}),undefined);assert.equal(math.getCombustionStats(bounds,{air:0,energy_cell:27}),undefined);});
function setup({ui=false,cap=1e9}={}){const r=registry(),events={},items=new Map(),values=new Map(),runtimes=new Map(),particles=[];let buttons,handler,writes=0;
class ItemStack{constructor(typeId,amount=1){this.typeId=typeId;this.amount=amount;}}
const inventory={getItem:k=>items.get(k),setItem(k,v){writes++;if(v)items.set(k,v);else items.delete(k);}};
const dimension={getBlock:()=>({typeId:'minecraft:air'}),getEntities:()=>[entity],spawnParticle:(id,pos)=>particles.push({id,pos})};
const entity={id:'combustion-1',isValid:true,typeId:'utilitycraft:combustion_chamber',dimension,location:{x:0,y:1,z:2},getDynamicProperty:k=>values.get(k),setDynamicProperty:(k,v)=>values.set(k,v),getComponent:()=>({container:inventory})};
const energy={value:0,cap,get(){return this.value;},getFreeSpace(){return this.cap-this.value;},add(n){assert(n<=this.getFreeSpace()+1e-7);this.value+=n;},transferToNetwork(){}};
const signals=Object.fromEntries(['entityContainerOpened','playerBreakBlock','playerPlaceBlock','blockExplode'].map(n=>[n,{subscribe(fn){events[n]=fn;}}]));
let displayed=0,io=0;const context=vm.createContext({...math,...r.hm,world:{afterEvents:signals},system:{currentTick:0},ItemStack,runtimes,
 EnergyStorage:{formatEnergyToText:String},InterfaceManager:{registerInterface(id,config){buttons=config.buttons;},linkBlockInterface(){},linkEntityInterface(){},ensureEntityInterfaces(){}},registerLinkNodeIO(){},
 Multiblock:{EntityManager:{getControllerEntityFromBlock:()=>entity},DeactivationManager:{deactivateEntity(e){e.setDynamicProperty('dorios:state','off');e.setDynamicProperty('dorios:bounds',undefined);}}},
 MultiblockGenerator:class{constructor(){this.valid=true;this.entity=entity;this.energy=energy;this.container=inventory;this.processingInterval=4;this.shouldUpdateUI=ui;}processIO(){throw new Error('Multiblock IO must be handled by ports');}displayEnergy(){displayed++;}},
 DoriosLib:{registry:{blockComponent(id,h){handler=h;}},text:{formatIdentifier:s=>s}},console});
const api=load('BP/scripts/machinery/generators/combustionChamber.js',context,['activateCombustion','tickCombustion','getCombustionData']);
values.set('dorios:state','on');values.set('dorios:bounds',JSON.stringify(bounds));api.activateCombustion({entity,components:{air:26,energy_cell:1,vent:1},structure:{bounds,ventBlocks:[{x:1,y:4,z:1}]},energyCap:cap});writes=0;items.set(21,new ItemStack('minecraft:coal',64));
return{entity,energy,items,values,runtimes,events,particles,buttons,api,context,get writes(){return writes;},get displayed(){return displayed;},tick(){context.system.currentTick+=4;api.tickCombustion({});},state:()=>api.getCombustionData(entity)};}
test('Power, closed UI and full energy preserve inventory and prepaid reserve',()=>{const x=setup();x.tick();assert.equal(x.energy.value,0);assert.equal(x.writes,0);x.buttons.power.onPress({entity:x.entity});x.tick();near(x.energy.value,160);assert.equal(x.items.get(21).amount,63);assert.equal(x.writes,1);assert.equal(x.displayed,0);const reserve=x.state().reserve;x.energy.cap=x.energy.value;x.tick();near(x.state().reserve,reserve);assert.equal(x.items.get(21).amount,63);});
test('Cache loss restores fuel and native UI, apply clamps rate and interior edits stop burning',()=>{const x=setup({ui:true});x.buttons.power.onPress({entity:x.entity});x.tick();const before=x.state().reserve;x.runtimes.clear();near(x.state().reserve,before);assert(x.items.get(2).typeId.startsWith('utilitycraft:fuel_bar_'));assert.equal(x.displayed,1);x.buttons.clear.onPress({entity:x.entity});x.buttons.key_9.onPress({entity:x.entity});x.buttons.key_9.onPress({entity:x.entity});x.buttons.key_9.onPress({entity:x.entity});x.buttons.key_9.onPress({entity:x.entity});x.buttons.apply.onPress({entity:x.entity});assert.equal(x.state().rate,3328);x.events.playerPlaceBlock({block:{dimension:x.entity.dimension,location:{x:2,y:2,z:2}}});const energy=x.energy.value;x.tick();assert.equal(x.energy.value,energy);assert.equal(x.state().enabled,false);});
test('Reactivation updates stats but retains partially burned fuel',()=>{const x=setup();x.buttons.power.onPress({entity:x.entity});x.tick();const reserve=x.state().reserve;x.api.activateCombustion({entity:x.entity,components:{air:25,energy_cell:2,vent:1},structure:{bounds,ventBlocks:[]},energyCap:2000});near(x.state().reserve,reserve);assert.equal(x.state().maxRate,3200);assert.equal(x.state().enabled,false);});
test('Controller, recipe, UI and texture dependencies are wired',()=>{const json=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));const bp=json('BP/blocks/multiblock/combustion_chamber/combustion_chamber_controller.json')['minecraft:block'];assert.deepEqual(bp.components['minecraft:tick'].interval_range,[4,4]);assert(bp.components['utilitycraft:combustion_chamber']);const terrain=json('RP/textures/terrain_texture.json').texture_data;for(const mat of Object.values(bp.components['minecraft:material_instances']))assert(fs.existsSync(path.join(root,'RP',terrain[mat.texture].textures+'.png')));const ui=json('RP/ui/combustion_chamber.json'),lang=fs.readFileSync(path.join(root,'RP/texts/en_US.lang'),'utf8');for(const key of JSON.stringify(ui).match(/ui\.hm\.cc\.[a-z_]+/g))assert(lang.includes(key+'='),key);assert(JSON.stringify(json('RP/ui/chest_screen.json')).includes('combustion_chamber.utilitycraft_panel'));assert(json('RP/ui/_ui_defs.json').ui_defs.includes('ui/combustion_chamber.json'));const all=JSON.stringify(ui);assert(all.includes('fuel_inventory'));assert(!all.includes('gas_turbine'));assert.equal(json('BP/recipes/controllers/combustion_chamber_controller.json')['minecraft:recipe_shaped'].key.X.item,'utilitycraft:expert_furnator');});

test('Interior flames are sparse, stay inside bounds and do not inspect blocks',()=>{const x=setup();x.tick();assert.equal(x.particles.length,0);x.buttons.power.onPress({entity:x.entity});x.tick();const flames=x.particles.filter(p=>p.id==='minecraft:basic_flame_particle');assert.equal(flames.length,3);for(const {pos} of flames)for(const axis of ['x','y','z'])assert(pos[axis]>1&&pos[axis]<4);x.tick();assert.equal(x.particles.filter(p=>p.id==='minecraft:basic_flame_particle').length,3);let blockReads=0;x.entity.dimension.getBlock=()=>{blockReads++;return {typeId:'utilitycraft:energy_cell'};};for(let i=0;i<5;i++)x.tick();assert.equal(x.particles.filter(p=>p.id==='minecraft:basic_flame_particle').length,6);assert.equal(blockReads,0);x.entity.dimension.getBlock=()=>({typeId:'minecraft:air'});x.state().rate=x.state().maxRate;for(let i=0;i<5;i++)x.tick();assert.equal(x.particles.filter(p=>p.id==='minecraft:basic_flame_particle').length,11);});
